[package]
name = "seedwing-mvp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# my signed package
#sigstore = "0.6.0"
a1 = "0.1.1"

# my unsigned package
#ip-spoofing = "0.1.0"
